### PR TITLE
Fix channel issues with HTTP server shutdown

### PR DESCRIPTION
**Pull request by zealws**
The `wg.Done()` channel was being read from in more than one place, which is bad, since only one value is ever written to this channel. A panic in the right place (such as pkg/output/http_writer.go:62) can cause the HTTP server to wait forever for workers to shutdown that will never shutdown, since they never receive a value on the `wg.Done()` channel.

To resolve this issue, I modified the HTTPWriter functions in the following way:
- workers now listen for shutdown signals (empty structs) on a dedicated channel named `workerShutdownSignals`. Upon receiving a value, the worker shuts down gracefully.
- when the HTTPWriter is cancelled (or a SIGINT is received), we send one empty struct to the `workerShutdownSignals` for each worker. Each worker reads a single value and shuts down.
- I also modified the `recover` hook in `HTTPWriter.Write` to call `cancel`, triggering the worker shutdowns. This also required saving the `CancelFunc` on the struct so it could be called in this new place.

Also, I added some logging which illustrates this workflow when it happens.

I considered adding a test to this. In order to do so, the test would need to do two things:
1. Cause a `panic` in `HTTPWriter.Write`.
2. Detect that the process exited correctly.

`1` could be achieved with a callback function on the `HTTPWriter` struct which the test injects a `panic` into.
`2` is much more difficult, since the proper shutdown procedure involves `os.Exit`, it would be difficult to catch that from within the same process.

Ultimately I decided the level of complexity for a test that either overloads `os.Exit` somehow or catches it would be overkill, so I did not add a test, but I could pursue a different approach if you think it's helpful.

So I tested this manually by adding `panic("foo bar")` in `HTTPWriter.Write` (after the `defer`) and ensuring the processes shut down properly:
```
# sudo ./pauditd -config pauditd.yaml
Flushed existing audit rules
Added audit rule #1
Added audit rule #2
Added audit rule #3
Added audit rule #4
Socket receive buffer size: 32768
Started processing events in the range [1300, 1399]
pkg: foo bar
Waiting for goroutines to complete
cancel() called! Shutting down
Shutting down 10 workers...
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Goroutines completed
```

I also made sure SIGINT still worked:
```
# sudo ./pauditd -config pauditd.yaml
Flushed existing audit rules
Added audit rule #1
Added audit rule #2
Added audit rule #3
Added audit rule #4
Socket receive buffer size: 32768
Started processing events in the range [1300, 1399]
HTTPWriter.Process could not send request: Post "https://service-url/service": dial tcp: lookup service-url: no such host
^C
Received signal interrupt
Shutting down 10 workers...
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Worker shutting down!
Waiting for goroutines to complete
Goroutines completed
```

### CODE REVIEW

**Comment by zealws** [comment]
cc @Hornswoggles @jburianek :smile:

**Comment by zealws** [comment]
This PR fixes issue #20

**Comment by joemiller** [comment]
awesome

**Review by joemiller — APPROVED** [review]

**Review by Hornswoggles — APPROVED** [review]
+1

**Review by jburianek — APPROVED** [review]

**Pull request merged**
